WB-2008 providing plain text content to explorer for indexation
opendigitaleducation/blog pull request #17
Opened 2023-09-21 15:59 UTC by mariusode

Dans le cas de la création ou de la mise à jour de contenu de billets de blog, on récupère une version **plain text** (et non plus html) du contenu qui sera désormais transmis à l'explorateur pour l'indexation. Ce contenu plain text sera stocké dans un champ **content** de la base ES.

Ont dû être mis à jour :
- entcore : 
- explorer :

2023-09-25 13:40 UTC, juniorode commented on src/main/java/org/entcore/blog/explorer/PostExplorerPlugin.java
> +        if (source.containsKey("contentPlain")) {
En regardant bien ce bout de code je me dis que ça ça n'a rien de spécifique aux articles de blog et que du coup on pourrait le faire passer dans la classe abstraite, comme ça on n'aurait pas à répéter le même bout de code pour toutes les ressources

2023-09-25 13:49 UTC, juniorode commented on src/main/java/org/entcore/blog/services/impl/DefaultPostService.java
> +									new HashSet<>(Arrays.asList(ContentTransformerFormat.JSON, ContentTransformerFormat.PLAINTEXT)),
est-ce qu'il ne faudrait pas aussi récupérer l'HTML aussi, histoire d'être sûr d'avoir qqchose de bien propre ?

2023-09-25 13:50 UTC, juniorode commented on src/main/java/org/entcore/blog/services/impl/DefaultPostService.java
> +							validatedPost.put("jsonContent", response.result().getJsonContent());
et si c'est le cas (rapport au commentaire précédent), ajouter le `put` correspondant ici

2023-09-25 15:50 UTC, mariusode commented on src/main/java/org/entcore/blog/explorer/PostExplorerPlugin.java
> +        if (source.containsKey("contentPlain")) {
tu veux dire faire de ce bout de code l'implémentation par défaut dans ExplorerSubResource ?

2023-09-27 09:21 UTC, juniorode requested changes

2023-09-27 09:21 UTC, juniorode commented on src/main/java/org/entcore/blog/services/impl/DefaultPostService.java
> +							validatedPost.put("jsonContent", response.result().getJsonContent());
OK pour `l'update` mais du coup est-ce qu'il ne faudrait pas faire la même sur le `create` [ici](https://github.com/opendigitaleducation/blog/pull/17/files#diff-27dd05b8b831b7c39fa9d85fc684b7193ad49be942fb27134991044f92605d4eR129) ?

2023-09-27 09:25 UTC, mariusode commented on src/main/java/org/entcore/blog/services/impl/DefaultPostService.java
> +							validatedPost.put("jsonContent", response.result().getJsonContent());
Je me suis dis que dans le cas du `create` le front nous fournirait forcément du contenu HTML généré par TipTap, donc "clean". Mais peut-être qu'un cas m'échappe ?

2023-09-27 12:15 UTC, juniorode approved these changes

2023-09-27 13:14 UTC, merged